### ISSUE TITLE
Sidebar and main content is overlapping

### ISSUE THREAD

**Issue by wtzr** [creativetimofficial/soft-ui-dashboard-django#2]
https://www.creative-tim.com/new-issue/soft-ui-dashboard

This issue can also be reproduced on your own demo website --> https://www.creative-tim.com/live/soft-ui-dashboard-pro-django

To reproduce. 
1. go to link https://www.creative-tim.com/live/soft-ui-dashboard-pro-django
2. switch between dashboards, for example 'automotive' and 'smart home'
3. Notice that sometimes the main content goes behind the sidebar. 

In our package, we experience the exact same problem. Would be great to know how to prevent the main content overlapping the sidebar. 

Attached a screenshot, in case you can't reproduce. 

![Screenshot (51)](https://user-images.githubusercontent.com/4520190/195594590-23b39ac7-3cce-45d0-8aea-986e87621775.png)

**Comment by app-generator** [comment]
Solved in AppSeed support (discord).
